import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CssBaseline from '@mui/material/CssBaseline';
import { Lato } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@mui/material';
import { theme } from '@/lib/theme';
import { MyContextProvider } from '@/context/useContextMenu';


const lato = Lato({ weight: "400", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id='__next' className={lato.className}>
        <AppRouterCacheProvider>
          <MyContextProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              {children}
            </ThemeProvider>
          </MyContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
