import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CssBaseline from '@mui/material/CssBaseline';
import { Lato } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from '@/context/useContextMenu';
import { cn } from '@/lib/utils';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';


const lato = Lato({ weight: "400", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id='__next' className={cn(`relative`, lato.className)}>
        <AppRouterCacheProvider>
          <MyContextProvider>
            <CssBaseline />
            <Header />
            <main className="flex min-h-screen flex-col items-center justify-between">
              {children}
            </main>
            <Footer />
          </MyContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
